// Code generated by SQLBoiler 4.14.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

var TableNames = struct {
	Issues       string
	Projectcards string
	Projects     string
	Pullrequests string
	Repositories string
	Users        string
}{
	Issues:       "issues",
	Projectcards: "projectcards",
	Projects:     "projects",
	Pullrequests: "pullrequests",
	Repositories: "repositories",
	Users:        "users",
}
